# Generated by Django 5.2.4 on 2025-07-14 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0010_productrating_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviewed',
            new_name='review',
        ),
    ]
